version: '3'

services:

  database:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: framewa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
    - 8101:3306
    volumes:
      - ./.database:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8102:8080
