<form action="" method="POST"class="container bg-light my-5 py-3 rounded"style="height: 640px;">
  
     <br/><h2 class="text-center">Connexion</h2><br/>
  <div class="form-group">
    <label for="exampleInputEmail1" class="font-weight-bold" >Nickname</label>
    <input id="registerInput" class="form-control form-control-lg"style="height: 50px;" type="text" name="nickname">
  </div>
  
  <div class="form-group">
    <label for="exampleInputPassword1" class="font-weight-bold"  >Mot de Passe</label>
    <input for="password1" name="password" type="password" class="form-control" style="height: 50px;" id="exampleInputPassword1">
  </div>
  
 
  <a href="#">
    <button id="registerButton" type="submit" class="btn btn-primary bg-dark"  style="height: 50px;width: 100%;">
  Se connecter </button> </a>
  
  <form/>
  