
<form action="" method="POST"class="container bg-light my-5 py-3 rounded"style="height: 640px;">
  <?php if (!empty($data['errors'])): ?>
    <?php foreach ($data['errors'] as $error): ?>
      <p style="color: red"><?= htmlentities($error) ?></p>
    <?php endforeach; ?>
  <?php endif; ?>
  
     <br/><h2 class="text-center">Inscription</h2><br/>
  <div class="form-group">
    <label for="exampleInputEmail1" class="font-weight-bold" >Nickname</label>
    <input id="registerInput" class="form-control form-control-lg"name="nickname">
  </div>
  
  <div class="form-group">
    <label for="exampleInputPassword1" class="font-weight-bold"  >Mot de Passe</label>
    <input for="password1" name="password1" type="password" class="form-control" style="height: 50px;" id="exampleInputPassword1">
  </div>
  
   <div class="form-group">
    <label for="exampleInputPassword1" class="font-weight-bold">Répétez le Mot de Passe</label>
    <input for="password2" name="password2" type="password" class="form-control"style="height: 50px;" id="exampleInputPassword1">
  </div>
  
 
  <button id="registerButton" type="submit" class="btn btn-primary bg-dark"  style="height: 50px;width: 100%;">S'inscrirre</button>
  
  <form/>
  