<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Boom!</title>
  <style>
    header {
      background-color: darkred;
      color: white;
      text-align: center;
    }
    section {
      background-color: darkred;
      color: white;
    }
    p {
      margin: 0;
    }
    blockquote {
      padding: 8px;
      background-color: #777777;
      font-size: 24px;
    }
    h3 {
      margin-bottom: 2px;
      border-bottom: 1px solid white;
    }
    ul {
      padding: 0;
    }
    li {
      list-style: none;
      padding: 12px;
    }
  </style>
</head>
<body>
  <header>
    <h1>/!\</h1>
  </header>

  <main>
    <section>
      <h2>Something went wrong.</h2>
      <blockquote>
        <strong><?= htmlentities($exception->getMessage()) ?></strong>
      </blockquote>
      <p>File: <strong><?= htmlentities($exception->getFile()) ?></strong></p>
      <p>Line: <strong><?= htmlentities($exception->getLine()) ?></strong></p>
    </section>

    <hr/>

    <section>
      <h2>Trace:</h2>
        <?php if (!empty($exception->getTrace())): ?>
          <?php $i = count($exception->getTrace()) ?>
          <ul>
              <?php foreach ($exception->getTrace() as $node): ?>
                <li>
                  <h3><?= $i-- ?></h3>
                  <p>File: <strong><?= htmlentities($node['file']) ?></strong></p>
                  <p>Line: <strong><?= htmlentities($node['line']) ?></strong></p>
                  <p>Class: <strong><?= htmlentities($node['class']) ?></strong></p>
                  <p>Function: <strong><?= htmlentities($node['function']) ?></strong></p>
                </li>
              <?php endforeach; ?>
          </ul>
        <?php endif; ?>
    </section>
  </main>

</body>
</html>
